export const apiUrl:string = 'http://44.204.59.197:3000/api/v1/';
export const activePageName = ['Home', 'Students', 'Project', 'Toolbox', 'Forum', 'Account'];
export var activeUser = {
    email: "admin@tut.ac.za",
    title: "Prof",
    password: "tut4life",
    firstname: "Admin",
    lastname: "Shilaluke",
    department: "Informatics",
    userId: 1,
    userType: 1,
    description: "Admin",
};
export const users = [{
    email: "supervisor@tut.ac.za",
    title: "Prof",
    password: "tut4life",
    firstname: "Supervisor",
    lastname: "Nyembe",
    department: "Informatics",
    userId: 2,
    userType: 2,
    description: "Supervisor",
},{
    email: "student@tut.ac.za",
    title: "Student",
    password: "tut4life",
    firstname: "Student",
    lastname: "Paledi",
    department: "Informatics",
    userId: 3,
    userType: 3,
    description: "Student",
},{
    email: "admin@tut.ac.za",
    title: "Prof",
    password: "tut4life",
    firstname: "Admin",
    lastname: "Shilaluke",
    department: "Informatics",
    userId: 1,
    userType: 1,
    description: "Admin"
}]

export const studentsList = [
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955961", firstName: "Shiko",lastName: "Matlala", supervisorId: {status: true, supervisorId: "280233"}, startDate: "Tue 04 Oct 2022", studentComplains: 1},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216923960", firstName: "Lerato",lastName: "Marokoane", supervisorId: {status: true, supervisorId: "280233"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955967", firstName: "James",lastName: "Livingston", supervisorId: {status: true, supervisorId: "280233"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "219525596", firstName: "Wisani",lastName: "Maluleka", supervisorId: {status: true, supervisorId: "280233"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "289545960", firstName: "Mashoto",lastName: "Tema", supervisorId: {status: true, supervisorId: "280233"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955701", firstName: "Noxolo",lastName: "Moletsane", supervisorId: {status: true, supervisorId: "298323"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955496", firstName: "Moletsane",lastName: "Keith", supervisorId: {status: true, supervisorId: "298323"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "George",lastName: "Lusanda", supervisorId: {status: true, supervisorId: "280233"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Isabel",lastName: "Malatji", supervisorId: {status: true, supervisorId: "092122"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Tsholofelo",lastName: "Masemene", supervisorId: {status: false, supervisorId: "Unassigned"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Itumeleng",lastName: "Matlala", supervisorId: {status: false, supervisorId: "Unassigned"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Musa",lastName: "Tshoma", supervisorId: {status: false, supervisorId: "Unassigned"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Mercy",lastName: "Pitsi", supervisorId: {status: true, supervisorId: "092122"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Mohau",lastName: "Selamolela", supervisorId: {status: false, supervisorId: "Unassigned"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Kody",lastName: "Martin", supervisorId: {status: true, supervisorId: "280233"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Zack",lastName: "Rowe", supervisorId: {status: true, supervisorId: "280233"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Rowe",lastName: "Henly", supervisorId: {status: true, supervisorId: "280233"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Katleho",lastName: "Molwelang", supervisorId: {status: false, supervisorId: "Unassigned"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Makhoba",lastName: "Thato", supervisorId: {status: false, supervisorId: "Unassigned"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Jack",lastName: "Letswalo", supervisorId: {status: false, supervisorId: "Unassigned"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Mo",lastName: "Mawela", supervisorId: {status: false, supervisorId: "Unassigned"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Monique",lastName: "Matlala", supervisorId: {status: false, supervisorId: "Unassigned"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Molemo",lastName: "Mokaleng", supervisorId: {status: false, supervisorId: "Unassigned"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Doctor",lastName: "Malinga", supervisorId: {status: true, supervisorId: "280233"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Daniel",lastName: "Tshimo", supervisorId: {status: true, supervisorId: "280233"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Joshep",lastName: "Smith", supervisorId: {status: true, supervisorId: "280233"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Jill",lastName: "Scott", supervisorId: {status: true, supervisorId: "280233"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Shiko",lastName: "Matlala", supervisorId: {status: false, supervisorId: "Unassigned"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Shiko",lastName: "Matlala", supervisorId: {status: false, supervisorId: "Unassigned"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Shiko",lastName: "Matlala", supervisorId: {status: false, supervisorId: "Unassigned"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Shiko",lastName: "Matlala", supervisorId: {status: true, supervisorId: "280233"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Shiko",lastName: "Matlala", supervisorId: {status: true, supervisorId: "280233"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Shiko",lastName: "Matlala", supervisorId: {status: true, supervisorId: "773222"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Shiko",lastName: "Matlala", supervisorId: {status: false, supervisorId: "Unassigned"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Shiko",lastName: "Matlala", supervisorId: {status: false, supervisorId: "Unassigned"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Shiko",lastName: "Matlala", supervisorId: {status: false, supervisorId: "Unassigned"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Shiko",lastName: "Matlala", supervisorId: {status: true, supervisorId: "773222"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Shiko",lastName: "Matlala", supervisorId: {status: true, supervisorId: "280233"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Shiko",lastName: "Matlala", supervisorId: {status: true, supervisorId: "280233"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Shiko",lastName: "Matlala", supervisorId: {status: true, supervisorId: "773222"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Shiko",lastName: "Matlala", supervisorId: {status: false, supervisorId: "Unassigned"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Shiko",lastName: "Matlala", supervisorId: {status: false, supervisorId: "Unassigned"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Shiko",lastName: "Matlala", supervisorId: {status: false, supervisorId: "Unassigned"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Shiko",lastName: "Matlala", supervisorId: {status: false, supervisorId: "Unassigned"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Shiko",lastName: "Matlala", supervisorId: {status: false, supervisorId: "Unassigned"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Shiko",lastName: "Matlala", supervisorId: {status: false, supervisorId: "Unassigned"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Shiko",lastName: "Matlala", supervisorId: {status: false, supervisorId: "Unassigned"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Shiko",lastName: "Matlala", supervisorId: {status: false, supervisorId: "Unassigned"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Shiko",lastName: "Matlala", supervisorId: {status: false, supervisorId: "Unassigned"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Shiko",lastName: "Matlala", supervisorId: {status: false, supervisorId: "Unassigned"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Shiko",lastName: "Matlala", supervisorId: {status: true, supervisorId: "827232"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Shiko",lastName: "Matlala", supervisorId: {status: true, supervisorId: "280233"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Shiko",lastName: "Matlala", supervisorId: {status: true, supervisorId: "280233"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},
  { studentCount: 1, projectName: "Lorem ipsum", studNumber: "216955960", firstName: "Shiko",lastName: "Matlala", supervisorId: {status: false, supervisorId: "Unassigned"}, startDate: "Tue 04 Oct 2022", studentComplains: 0},]
